# Generated by Django 2.2.10 on 2021-11-03 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_hojasdevida_correo'),
    ]

    operations = [
        migrations.AddField(
            model_name='hojasdevida',
            name='telefono',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
