# Generated by Django 2.2.10 on 2021-11-09 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_hojasdevida_departamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requerimiento',
            name='OC',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='requerimiento',
            name='fecha_oc',
            field=models.DateField(blank=True, null=True),
        ),
    ]
