# Generated by Django 2.2.10 on 2021-11-09 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20211109_0006'),
    ]

    operations = [
        migrations.AddField(
            model_name='capacitaciones',
            name='adjunto',
            field=models.FileField(default=1, upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='capacitaciones',
            name='duracion',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='capacitaciones',
            name='evaluacion',
            field=models.TextField(default=11),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='capacitaciones',
            name='objetivo',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='capacitaciones',
            name='responsable',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='capacitaciones',
            name='surge',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='capacitaciones',
            name='tipo',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='capacitaciones',
            name='tema',
            field=models.TextField(),
        ),
    ]
