# Generated by Django 2.2.10 on 2021-11-09 07:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20211109_0242'),
    ]

    operations = [
        migrations.AddField(
            model_name='capacitaciones',
            name='tema_texto',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='capacitaciones',
            name='tema',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.Temas'),
        ),
    ]
