# Generated by Django 2.2.10 on 2021-11-09 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20211109_0257'),
    ]

    operations = [
        migrations.AddField(
            model_name='capacitaciones',
            name='evaluacion_texto',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
