# Generated by Django 2.2.10 on 2021-11-17 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_capacitaciones_evaluacion_texto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordencompra',
            name='proveedor',
        ),
        migrations.AddField(
            model_name='ordencompra',
            name='proveedor_1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proveedor_1', to='app.Proveedores'),
        ),
        migrations.AddField(
            model_name='ordencompra',
            name='proveedor_2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proveedor_2', to='app.Proveedores'),
        ),
        migrations.AddField(
            model_name='ordencompra',
            name='proveedor_3',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proveedor_3', to='app.Proveedores'),
        ),
    ]
