# Generated by Django 2.2.10 on 2021-11-17 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20211117_0912'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordencompra',
            old_name='cotizacion',
            new_name='cotizacion_1',
        ),
        migrations.AddField(
            model_name='ordencompra',
            name='cotizacion_2',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='ordencompra',
            name='cotizacion_3',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
