# Generated by Django 2.2.10 on 2021-11-28 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20211117_0917'),
    ]

    operations = [
        migrations.AddField(
            model_name='requerimiento',
            name='sugerencia_proveedor1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='requerimiento',
            name='sugerencia_proveedor2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='requerimiento',
            name='sugerencia_proveedor3',
            field=models.TextField(blank=True, null=True),
        ),
    ]
