# Generated by Django 2.2.10 on 2021-11-28 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20211128_1650'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductosRequerimiento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.TextField()),
                ('cantidad', models.IntegerField()),
                ('unidades', models.TextField()),
                ('valor_unitario', models.IntegerField(blank=True, null=True)),
                ('iva', models.IntegerField(blank=True, null=True)),
                ('valor_iva', models.IntegerField(blank=True, null=True)),
                ('valor_total', models.IntegerField(blank=True, null=True)),
                ('requerimiento_relacionado', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
