# Generated by Django 2.2.10 on 2021-12-12 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_productosrequerimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='productosservicios',
            name='requerimiento_relacionado',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
