# Generated by Django 2.2.10 on 2021-12-12 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_productosservicios_requerimiento_relacionado'),
    ]

    operations = [
        migrations.AddField(
            model_name='productosrequerimiento',
            name='calibracion',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productosrequerimiento',
            name='reembolsable',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
