# Generated by Django 2.2.10 on 2021-12-12 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20211212_1739'),
    ]

    operations = [
        migrations.AddField(
            model_name='productosservicios',
            name='calibracion',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productosservicios',
            name='reembolsable',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
