# Generated by Django 2.2.10 on 2021-12-13 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_imagenrequerimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagenrequerimiento',
            name='requerimiento_relacionado',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
