# Generated by Django 2.2.10 on 2021-12-21 00:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_imagenrequerimiento_requerimiento_relacionado'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordencompra',
            old_name='cotizacion_1',
            new_name='cotizacion',
        ),
        migrations.RemoveField(
            model_name='ordencompra',
            name='cotizacion_2',
        ),
        migrations.RemoveField(
            model_name='ordencompra',
            name='cotizacion_3',
        ),
        migrations.RemoveField(
            model_name='ordencompra',
            name='proveedor_1',
        ),
        migrations.RemoveField(
            model_name='ordencompra',
            name='proveedor_2',
        ),
        migrations.RemoveField(
            model_name='ordencompra',
            name='proveedor_3',
        ),
        migrations.AddField(
            model_name='ordencompra',
            name='proveedor',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='solicitudesc',
            name='cotizacion_1',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='solicitudesc',
            name='cotizacion_2',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='solicitudesc',
            name='cotizacion_3',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='solicitudesc',
            name='proveedor_1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proveedor_1', to='app.Proveedores'),
        ),
        migrations.AddField(
            model_name='solicitudesc',
            name='proveedor_2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proveedor_2', to='app.Proveedores'),
        ),
        migrations.AddField(
            model_name='solicitudesc',
            name='proveedor_3',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proveedor_3', to='app.Proveedores'),
        ),
    ]
