# Generated by Django 2.2.10 on 2021-12-21 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_auto_20211220_1907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudesc',
            name='descripcion',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='solicitudesc',
            name='proveedor_1',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='solicitudesc',
            name='proveedor_2',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='solicitudesc',
            name='proveedor_3',
            field=models.TextField(null=True),
        ),
    ]
