# Generated by Django 2.2.10 on 2021-12-21 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_auto_20211220_1910'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudesc',
            name='proveedor_seleccionado',
            field=models.TextField(blank=True, null=True),
        ),
    ]
