# Generated by Django 2.2.10 on 2021-12-21 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_solicitudesc_proveedor_seleccionado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordencompra',
            name='aprueba',
        ),
    ]
