# Generated by Django 2.2.10 on 2022-02-08 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_remove_ordencompra_aprueba'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalificacionProveedores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.TextField()),
                ('peso', models.IntegerField()),
            ],
        ),
    ]
