# Generated by Django 2.2.10 on 2022-03-01 21:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_calificacionesproveedores_fecha'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubCategoriasCalificacion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('peso', models.IntegerField()),
                ('categoria_principal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.CalificacionProveedores')),
            ],
        ),
    ]
