# Generated by Django 2.2.10 on 2022-03-03 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_calificacionesproveedores_sub_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calificacionesproveedores',
            name='calificacion',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
