# Generated by Django 2.2.10 on 2022-03-23 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_auto_20220302_2050'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='capacitaciones',
            name='surge',
        ),
    ]
