# Generated by Django 2.2.10 on 2022-03-23 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0034_auto_20220323_0014'),
    ]

    operations = [
        migrations.AddField(
            model_name='ausentismo',
            name='detalle',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ausentismo',
            name='duracion_cantidad',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ausentismo',
            name='duracion_unidad',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ausentismo',
            name='estado',
            field=models.TextField(default='Creada'),
        ),
    ]
