# Generated by Django 2.2.10 on 2022-03-23 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0035_auto_20220323_0021'),
    ]

    operations = [
        migrations.AddField(
            model_name='ausentismo',
            name='adjunto',
            field=models.FileField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
