# Generated by Django 2.2.10 on 2022-03-23 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0037_auto_20220323_0041'),
    ]

    operations = [
        migrations.CreateModel(
            name='AsistenciaCapacitacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Presence', models.BooleanField(default=False)),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.HojasdeVida')),
            ],
        ),
    ]
