# Generated by Django 2.2.10 on 2022-04-18 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0038_asistenciacapacitacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hojasdevida',
            name='cesantias',
        ),
        migrations.RemoveField(
            model_name='hojasdevida',
            name='hoja_vida',
        ),
        migrations.RemoveField(
            model_name='hojasdevida',
            name='nomina',
        ),
        migrations.RemoveField(
            model_name='hojasdevida',
            name='salud_trabajo',
        ),
        migrations.RemoveField(
            model_name='hojasdevida',
            name='seguridad_social',
        ),
        migrations.RemoveField(
            model_name='hojasdevida',
            name='tthh',
        ),
    ]
