# Generated by Django 2.2.10 on 2022-04-18 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0040_auto_20220417_1925'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentosHojaVida',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hoja_relacionada', models.IntegerField(blank=True)),
                ('descripcion', models.TextField()),
                ('documento', models.FileField(upload_to='')),
            ],
        ),
    ]
