# Generated by Django 2.2.10 on 2022-04-18 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0041_documentoshojavida'),
    ]

    operations = [
        migrations.AddField(
            model_name='ausentismo',
            name='codigo_enfermedad',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
