# Generated by Django 2.2.10 on 2022-04-18 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0042_ausentismo_codigo_enfermedad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ausentismo',
            name='duracion_cantidad',
            field=models.TextField(),
        ),
    ]
