# Generated by Django 2.2.10 on 2022-04-26 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0044_auto_20220417_2303'),
    ]

    operations = [
        migrations.AddField(
            model_name='ausentismo',
            name='hora_final',
            field=models.TimeField(default='10:45'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ausentismo',
            name='hora_inicio',
            field=models.TimeField(default='10:45'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hojasdevida',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
