# Generated by Django 2.2.10 on 2022-04-26 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0045_auto_20220426_1658'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ausentismo',
            name='hora_final',
        ),
        migrations.RemoveField(
            model_name='ausentismo',
            name='hora_inicio',
        ),
        migrations.AlterField(
            model_name='ausentismo',
            name='adjunto',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='ausentismo',
            name='duracion_cantidad',
            field=models.TextField(blank=True, null=True),
        ),
    ]
