# Generated by Django 2.2.10 on 2022-04-26 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0046_auto_20220426_1700'),
    ]

    operations = [
        migrations.AddField(
            model_name='ausentismo',
            name='hora_final',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ausentismo',
            name='hora_inicio',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
