# Generated by Django 2.2.10 on 2022-04-26 22:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0047_auto_20220426_1702'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ausentismo',
            name='solicitado',
        ),
        migrations.AddField(
            model_name='ausentismo',
            name='solicitado',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.HojasdeVida'),
            preserve_default=False,
        ),
    ]
