# Generated by Django 2.2.10 on 2022-04-26 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0048_auto_20220426_1733'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ausentismo',
            name='solicitado',
        ),
        migrations.AddField(
            model_name='ausentismo',
            name='solicitado',
            field=models.ManyToManyField(to='app.HojasdeVida'),
        ),
    ]
