# Generated by Django 2.2.10 on 2022-04-26 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0049_auto_20220426_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asistenciacapacitacion',
            name='persona',
            field=models.TextField(),
        ),
    ]
