# Generated by Django 2.2.10 on 2022-04-26 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0050_auto_20220426_1814'),
    ]

    operations = [
        migrations.AddField(
            model_name='asistenciacapacitacion',
            name='capacitacion_relacionada',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
