# Generated by Django 2.2.10 on 2022-04-27 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0051_asistenciacapacitacion_capacitacion_relacionada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asistenciacapacitacion',
            name='capacitacion_relacionada',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='asistenciacapacitacion',
            name='persona',
            field=models.TextField(blank=True, null=True),
        ),
    ]
