# Generated by Django 2.2.10 on 2022-04-27 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0052_auto_20220426_2308'),
    ]

    operations = [
        migrations.AddField(
            model_name='asistenciacapacitacion',
            name='invitacion',
            field=models.BooleanField(default=False),
        ),
    ]
