# Generated by Django 2.2.10 on 2022-04-27 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0053_asistenciacapacitacion_invitacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='asistenciacapacitacion',
            name='calificacion',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
