# Generated by Django 2.2.10 on 2022-04-27 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0054_asistenciacapacitacion_calificacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asistenciacapacitacion',
            name='calificacion',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
