# Generated by Django 2.2.10 on 2022-04-27 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0055_auto_20220427_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ausentismo',
            name='hora_final',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ausentismo',
            name='hora_inicio',
            field=models.TextField(blank=True, null=True),
        ),
    ]
