# Generated by Django 3.2.8 on 2022-12-12 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0057_auto_20221212_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ausentismo',
            name='adjunto',
            field=models.FileField(blank=True, null=True, upload_to='Adjuntos_Ausentismo'),
        ),
        migrations.AlterField(
            model_name='capacitaciones',
            name='adjunto',
            field=models.FileField(blank=True, null=True, upload_to='Adjunto_Capacitaciones'),
        ),
        migrations.AlterField(
            model_name='cotizaciones',
            name='documento',
            field=models.FileField(upload_to='Cotizaciones'),
        ),
        migrations.AlterField(
            model_name='documentos',
            name='adjunto',
            field=models.FileField(upload_to='Documentos'),
        ),
        migrations.AlterField(
            model_name='documentoshojavida',
            name='documento',
            field=models.FileField(upload_to='Documentos_HojaVida'),
        ),
        migrations.AlterField(
            model_name='ordencompra',
            name='cotizacion',
            field=models.FileField(null=True, upload_to='Cotizacion_OrdenCompra'),
        ),
        migrations.AlterField(
            model_name='proveedores',
            name='camara_comercio',
            field=models.FileField(blank=True, null=True, upload_to='Proveedores_CamaraComercio'),
        ),
        migrations.AlterField(
            model_name='proveedores',
            name='cedula_representante',
            field=models.FileField(blank=True, null=True, upload_to='Proveedores_CCRepresentante'),
        ),
        migrations.AlterField(
            model_name='proveedores',
            name='certificacion_bancaria',
            field=models.FileField(blank=True, null=True, upload_to='Proveedores_CertificacionBancaria'),
        ),
        migrations.AlterField(
            model_name='proveedores',
            name='certificacion_comercial',
            field=models.FileField(blank=True, null=True, upload_to='Proveedores_CertificacionComercial'),
        ),
        migrations.AlterField(
            model_name='proveedores',
            name='iso_14001',
            field=models.FileField(blank=True, null=True, upload_to='Proveedores_ISO14001'),
        ),
        migrations.AlterField(
            model_name='proveedores',
            name='iso_9001',
            field=models.FileField(blank=True, null=True, upload_to='Proveedores_ISO9001'),
        ),
        migrations.AlterField(
            model_name='proveedores',
            name='ohsas_180001',
            field=models.FileField(blank=True, null=True, upload_to='Proveedores_OHSAS18001'),
        ),
        migrations.AlterField(
            model_name='proveedores',
            name='rut',
            field=models.FileField(blank=True, null=True, upload_to='Proveedores_RUT'),
        ),
        migrations.AlterField(
            model_name='proveedores',
            name='sg_sst',
            field=models.FileField(blank=True, null=True, upload_to='Proveedores_SGSST'),
        ),
        migrations.AlterField(
            model_name='solicitudesc',
            name='cotizacion_1',
            field=models.FileField(null=True, upload_to='Cotizaciones'),
        ),
        migrations.AlterField(
            model_name='solicitudesc',
            name='cotizacion_2',
            field=models.FileField(null=True, upload_to='Cotizaciones'),
        ),
        migrations.AlterField(
            model_name='solicitudesc',
            name='cotizacion_3',
            field=models.FileField(null=True, upload_to='Cotizaciones'),
        ),
        migrations.AlterField(
            model_name='solicitudesc',
            name='cuadro_comparativo',
            field=models.FileField(upload_to='Cotizaciones/CuadrosComparativosa'),
        ),
    ]
