# Generated by Django 3.2.8 on 2022-12-12 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0058_auto_20221212_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hojasdevida',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='fotosHojasVida'),
        ),
    ]
